settings:
  # What should happen if a folder is missing?
  # Possible values: retry, ignore, warn, error
  on_missing: retry

  # If on_missing is 'retry', how many seconds should pass between attempts?
  retry_delay: 5

  # [Optional] Interval to check that watched directories still exist
  # This is because of a bug with notify:
  # https://github.com/notify-rs/notify/issues/627
  liveness_interval: 10

folders:
  "./out":
    inputs:
      - "./in1"
      - "./in2"
      - "./in3"